### ISSUE TITLE
Identifier is super restrictive!

### ISSUE THREAD

**Issue by amanjpro** [postamar/anoa#3]
Any reason this restriction is applied?

```
Identifier           ::=  ['a'-'z'] ( '_' ['a'-'z'] | ['a'-'z''0'-'9'] )*
```

Why not simply:

```
Identifier           ::=  ['a'-'z'] ['_''a'-'z''0'-'9']*

```

**Comment by amanjpro** [comment]
ATM, I want to add a field (lets say named: `from_3p`) to a schema, and Anoa simply doesn't let me.

I cannot simply rename the field, as it comes from a third party, I have made the change locally to the parser, but wasn't sure if there is any reason it is disabled, will open a PR anyways.

**Comment by postamar** [comment]
I honestly can't remember the details but most restrictions are there to ensure cross-compatibility between avro, protobuf and thrift. IIRC forbidding words starting with digits was related to camel-casing somehow, something about name ambiguity.

In any case you usually want to own your schema somewhat and not be coupled too closely to a third-party's naming choices. It's for this reason that field aliases exist in anoa, and you might find them useful in your case: https://github.com/postamar/anoa/blob/a4a679be4057ab324e2a21c9be54120845d25eae/language/compiler/src/main/javacc/com/adgear/anoa/compiler/anoa_parser.jj#L362

Please let me know how that works out. Apologies for the belated response.

**Comment by amanjpro** [comment]
Hey!

It is good to hear from you. You are right, it is because protobuf's weird camel casing, and I have already opened a PR addressing this, here is the relevant commit:

https://github.com/postamar/anoa/pull/4/commits/819803d5c4cecd3aa389a3f5a8e4786430c33596

We actually ended up using my PR in prod, but will take a look into `FieldAlias` too
